name: Build Geode Mod

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: Windows
            os: windows-latest
            target: Win32
          - name: Android64
            os: ubuntu-latest
            target: Android64

    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Geode SDK
        uses: geode-sdk/actions/setup@main
        with:
          version: v2.0.0-beta.4

      - name: Configure CMake
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release -DGEODE_TARGET=${{ matrix.config.target }} -DGeode_DIR="${{ env.GEODE_SDK }}"

      - name: Build Mod
        run: |
          cmake --build build --config Release

      - name: Upload Artifact
        uses: actions/artifacts@v4
        with:
          name: ${{ matrix.config.name }}-build
          path: build/*.geode
